<?php

namespace Immobilisation\ImmobilisationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmmortissementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmmortissementsRepository extends EntityRepository
{
	/*public function calculproc()
	{
    	return $this->getEntityManager()
                ->getConnection()
                ->query(`calculerammort('1')`)
                ->fetchAll();
	}*/
	public function calculproc($id)
    {
		$a= $this->getEntityManager()
		->getConnection()
		->query('CALL calculerammort(@id)')
		->bindValue(':id',$id);
		//dump($a);
		return $a;
    }
}
