<?php

namespace Immobilisation\ImmobilisationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * utilisateurimmoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurimmoRepository extends EntityRepository
{
}
