<?php

namespace Ecommerce\EcommerceBundle\Entity;

/**
 * promotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class promotionRepository extends \Doctrine\ORM\EntityRepository
{
}
