<?php

namespace Ecommerce\EcommerceBundle\Entity;

/**
 * wishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wishlistRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.user =:array')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
    public function finddeletewishlist($id)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.id =:id')
                ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
     public function deleteArticle($id)
    {
        $q = $this
            ->createQueryBuilder()
            ->delete('wishlist', 'w')
            ->where('w.id = :wishlist_id')
            ->setParameter('wishlist_id', $id)
            ->getQuery()
        ;
 
        return 1 === $q->getScalarResult();
    }
}
