<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * markRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marqueRepository extends \Doctrine\ORM\EntityRepository
{
}
