<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * utilisateursadressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateursadressesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.utilisateur =:array')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
	
}
